### ISSUE TITLE
Output to data-scripts folder

### ISSUE THREAD

**Issue by necrogami** [dennisfokker/Factorio-Json-Calculator-Exporter-mod#1]
Can this maybe output a file to the data-scripts folder instead of outputing inline to the log file?

**Comment by dennisfokker** [comment]
Short answer: Sadly I cannot.
Long answer: For the calculator I want to make, I need icon data from e.g. items (file paths). This data is only available during the data stage (loading screen when you start up Factorio). During this stage (as far as I know) I can only write to the log or stdout (console) and not to custom files.

If you have a text editor which supports Regex you can use the following regex to extract the JSON object. It will be contained in group 1.
`\@__JsonCalculatorExporter__\/data-final-fixes\.lua\:\d+\: ({.+})\n\r?\s+\d+\.\d+ \w`
